version: "3"
services:
  data:
    image: virtualcommons/foraging:latest
    command: ant convert
    volumes:
      - ./docker/data:/code/experiment-data
      - ./docker/shared/build:/code/target
      - ./docker/shared/lib:/code/lib
  experiment:
    build: ./
    image: virtualcommons/foraging:latest
    ports:
      - "16001:16001"
    volumes:
      - ./docker/data:/code/experiment-data
      - ./docker/shared/html:/usr/share/nginx/html
      - ./docker/shared/build:/code/target
      - ./docker/shared/lib:/code/lib
        # FIXME: cram the current filesystem's ./src/main/resources/configuration into the container.. this is super
        # hacky but should work for the interim.
      - ./src/main/resources/configuration:/code/src/main/resources/configuration
    links:
      - web
  web:
    image: nginx:latest
    volumes:
      - ./docker/shared/html:/usr/share/nginx/html
    ports:
      - "80:80"
