version: "3"
services:
  experiment:
    build: ./
    image: virtualcommons/foraging
    ports:
      - "16001:16001"
    volumes:
      - ./docker/data:/code/experiment-data
      - ./docker/services/run.sh:/etc/service/foraging/run
    links:
      - web
  web:
    image: nginx:1-alpine
    volumes:
      - ./src/main/webapp:/usr/share/nginx/html
    ports:
      - "8080:80"
volumes:
  data:
