version: "2"
services:
  experiment:
    build: ./
    image: virtualcommons/foraging
    volumes:
      - ./:/code/
    ports:
      - "16001:16001"
    working_dir: /code
    entrypoint: "java -jar -server server.jar"
    links:
      - web
  data:
    image: virtualcommons/foraging
    volumes:
      - ./:/code/
    working_dir: /code
    entrypoint: "ant convert"
    environment:
      - DATA_DIR
      - XML
    links:
      - experiment
  web:
    image: nginx:1-alpine
    volumes:
      - ./src/main/webapp:/usr/share/nginx/html
    ports:
      - "8080:80"
